import { supabase } from '@/lib/supabase';
import { logger } from '@/lib/logger';
import type { Post, PostComment, AutoPostType } from '@/types';

interface PostRow {
  id: string;
  author_id: string;
  content: string;
  images: string[] | null;
  sport_tag: string | null;
  team_tag: string | null;
  match_tag: string | null;
  tournament_tag: string | null;
  is_auto_generated: boolean;
  auto_type: AutoPostType | null;
  likes_count: number;
  comments_count: number;
  created_at: string;
}

interface FeedRow extends PostRow {
  author_username: string;
  author_full_name: string;
  author_avatar: string | null;
  author_is_verified: boolean;
}

function mapFeedRowToPost(row: FeedRow, currentUserId?: string): Post {
  return {
    id: row.id,
    authorId: row.author_id,
    content: row.content || '',
    images: row.images || [],
    sportTag: row.sport_tag || undefined,
    teamTag: row.team_tag || undefined,
    matchTag: row.match_tag || undefined,
    tournamentTag: row.tournament_tag || undefined,
    isAutoGenerated: row.is_auto_generated || false,
    autoType: row.auto_type || undefined,
    likesCount: row.likes_count || 0,
    commentsCount: row.comments_count || 0,
    createdAt: new Date(row.created_at),
    authorUsername: row.author_username,
    authorFullName: row.author_full_name,
    authorAvatar: row.author_avatar || undefined,
    authorIsVerified: row.author_is_verified,
    hasLiked: false,
  };
}

function mapRowToPost(row: PostRow): Post {
  return {
    id: row.id,
    authorId: row.author_id,
    content: row.content || '',
    images: row.images || [],
    sportTag: row.sport_tag || undefined,
    teamTag: row.team_tag || undefined,
    matchTag: row.match_tag || undefined,
    tournamentTag: row.tournament_tag || undefined,
    isAutoGenerated: row.is_auto_generated || false,
    autoType: row.auto_type || undefined,
    likesCount: row.likes_count || 0,
    commentsCount: row.comments_count || 0,
    createdAt: new Date(row.created_at),
  };
}

export const postsApi = {
  async getFeed(userId: string, page: number = 1, limit: number = 20): Promise<{ posts: Post[]; hasMore: boolean }> {
    const offset = (page - 1) * limit;
    const { data, error } = await (supabase.rpc as any)('get_feed_posts', {
      p_user_id: userId,
      p_limit: limit,
      p_offset: offset,
    });

    if (error) {
      logger.error('PostsAPI', 'getFeed error:', error);
      throw error;
    }

    const rows = (data || []) as FeedRow[];
    const posts = rows.map((r) => mapFeedRowToPost(r, userId));

    if (posts.length > 0) {
      const postIds = posts.map((p) => p.id);
      const { data: likes } = await (supabase
        .from('post_likes')
        .select('post_id')
        .eq('user_id', userId)
        .in('post_id', postIds) as any);

      const likedPostIds = new Set(((likes || []) as { post_id: string }[]).map((l) => l.post_id));
      posts.forEach((p) => {
        p.hasLiked = likedPostIds.has(p.id);
      });
    }

    return { posts, hasMore: posts.length === limit };
  },

  async getPostsByUser(userId: string, page: number = 1, limit: number = 20): Promise<{ posts: Post[]; hasMore: boolean }> {
    const from = (page - 1) * limit;
    const to = from + limit - 1;

    const { data, error, count } = await (supabase
      .from('posts')
      .select('*', { count: 'exact' })
      .eq('author_id', userId)
      .order('created_at', { ascending: false })
      .range(from, to) as any);

    if (error) throw error;

    const posts = ((data || []) as PostRow[]).map(mapRowToPost);
    return { posts, hasMore: count ? from + limit < count : false };
  },

  async createPost(params: {
    authorId: string;
    content: string;
    images?: string[];
    sportTag?: string;
    teamTag?: string;
    matchTag?: string;
    tournamentTag?: string;
  }): Promise<Post> {
    logger.debug('PostsAPI', 'Creating post');
    const { data, error } = await (supabase
      .from('posts')
      .insert({
        author_id: params.authorId,
        content: params.content,
        images: params.images || [],
        sport_tag: params.sportTag || null,
        team_tag: params.teamTag || null,
        match_tag: params.matchTag || null,
        tournament_tag: params.tournamentTag || null,
        is_auto_generated: false,
      } as any)
      .select('*')
      .single() as any);

    if (error) throw error;
    return mapRowToPost(data as PostRow);
  },

  async createAutoPost(params: {
    authorId: string;
    content: string;
    autoType: AutoPostType;
    sportTag?: string;
    teamTag?: string;
    matchTag?: string;
    tournamentTag?: string;
  }): Promise<Post | null> {
    logger.debug('PostsAPI', 'Creating auto post:', params.autoType);
    const { data, error } = await (supabase
      .from('posts')
      .insert({
        author_id: params.authorId,
        content: params.content,
        images: [],
        sport_tag: params.sportTag || null,
        team_tag: params.teamTag || null,
        match_tag: params.matchTag || null,
        tournament_tag: params.tournamentTag || null,
        is_auto_generated: true,
        auto_type: params.autoType,
      } as any)
      .select('*')
      .single() as any);

    if (error) {
      logger.error('PostsAPI', 'createAutoPost error:', error);
      return null;
    }
    return mapRowToPost(data as PostRow);
  },

  async deletePost(postId: string, authorId: string): Promise<void> {
    const { error } = await (supabase
      .from('posts')
      .delete()
      .eq('id', postId)
      .eq('author_id', authorId) as any);

    if (error) throw error;
  },

  async likePost(userId: string, postId: string): Promise<void> {
    const { error } = await (supabase
      .from('post_likes')
      .insert({ post_id: postId, user_id: userId } as any) as any);

    if (error && error.code !== '23505') throw error;
  },

  async unlikePost(userId: string, postId: string): Promise<void> {
    const { error } = await (supabase
      .from('post_likes')
      .delete()
      .eq('post_id', postId)
      .eq('user_id', userId) as any);

    if (error) throw error;
  },

  async getComments(postId: string): Promise<PostComment[]> {
    const { data, error } = await (supabase
      .from('post_comments')
      .select('id, post_id, user_id, content, parent_comment_id, created_at')
      .eq('post_id', postId)
      .order('created_at', { ascending: true }) as any);

    if (error) throw error;

    const comments = ((data || []) as any[]).map((r) => ({
      id: r.id,
      postId: r.post_id,
      userId: r.user_id,
      content: r.content,
      parentCommentId: r.parent_comment_id || undefined,
      createdAt: new Date(r.created_at),
    })) as PostComment[];

    if (comments.length === 0) return comments;

    const userIds = [...new Set(comments.map((c) => c.userId))];
    const { data: users } = await (supabase
      .from('users')
      .select('id, username, full_name, avatar')
      .in('id', userIds) as any);

    const userMap = new Map<string, { username: string; fullName: string; avatar?: string }>();
    for (const u of (users || []) as any[]) {
      userMap.set(u.id, {
        username: u.username,
        fullName: u.full_name,
        avatar: u.avatar || undefined,
      });
    }

    comments.forEach((c) => {
      const u = userMap.get(c.userId);
      if (u) {
        c.username = u.username;
        c.fullName = u.fullName;
        c.avatar = u.avatar;
      }
    });

    return comments;
  },

  async addComment(postId: string, userId: string, content: string, parentCommentId?: string): Promise<PostComment> {
    const { data, error } = await (supabase
      .from('post_comments')
      .insert({
        post_id: postId,
        user_id: userId,
        content,
        parent_comment_id: parentCommentId || null,
      } as any)
      .select('id, post_id, user_id, content, parent_comment_id, created_at')
      .single() as any);

    if (error) throw error;

    const { data: user } = await (supabase
      .from('users')
      .select('username, full_name, avatar')
      .eq('id', userId)
      .single() as any);

    return {
      id: data.id,
      postId: data.post_id,
      userId: data.user_id,
      content: data.content,
      parentCommentId: data.parent_comment_id || undefined,
      createdAt: new Date(data.created_at),
      username: user?.username,
      fullName: user?.full_name,
      avatar: user?.avatar || undefined,
    };
  },

  async deleteComment(commentId: string, userId: string): Promise<void> {
    const { error } = await (supabase
      .from('post_comments')
      .delete()
      .eq('id', commentId)
      .eq('user_id', userId) as any);

    if (error) throw error;
  },

  // =============================================
  // ADMIN MODERATION FUNCTIONS
  // =============================================
  async getAllPosts(page: number = 1, limit: number = 20): Promise<{ posts: Post[]; hasMore: boolean; total: number }> {
    const from = (page - 1) * limit;
    const to = from + limit - 1;

    const { data, error, count } = await (supabase
      .from('posts')
      .select('*', { count: 'exact' })
      .order('created_at', { ascending: false })
      .range(from, to) as any);

    if (error) throw error;

    const posts = ((data || []) as PostRow[]).map(mapRowToPost);

    if (posts.length > 0) {
      const authorIds = [...new Set(posts.map((p) => p.authorId))];
      const { data: authors } = await (supabase
        .from('users')
        .select('id, username, full_name, avatar, is_verified')
        .in('id', authorIds) as any);

      const authorMap = new Map<string, { username: string; fullName: string; avatar?: string; isVerified: boolean }>();
      for (const a of (authors || []) as any[]) {
        authorMap.set(a.id, {
          username: a.username,
          fullName: a.full_name,
          avatar: a.avatar || undefined,
          isVerified: a.is_verified || false,
        });
      }

      posts.forEach((p) => {
        const a = authorMap.get(p.authorId);
        if (a) {
          p.authorUsername = a.username;
          p.authorFullName = a.fullName;
          p.authorAvatar = a.avatar;
          p.authorIsVerified = a.isVerified;
        }
      });
    }

    return { posts, hasMore: count ? from + limit < count : false, total: count || 0 };
  },

  async reportPost(postId: string, reporterId: string, reason: string): Promise<void> {
    const { error } = await (supabase
      .from('post_reports')
      .insert({ post_id: postId, reporter_id: reporterId, reason } as any) as any);

    if (error && error.code !== '23505') throw error;

    // Send notification to post author
    try {
      const { data: post } = await (supabase
        .from('posts')
        .select('author_id, content')
        .eq('id', postId)
        .single() as any);

      if (post?.author_id && post.author_id !== reporterId) {
        const { notificationsApi } = await import('@/lib/api/notifications');
        const preview = (post.content || '').slice(0, 50);
        await notificationsApi.send(post.author_id, {
          type: 'social',
          title: 'Signalement reçu',
          message: `Votre post "${preview}${preview.length === 50 ? '...' : ''}" a été signalé.`,
          data: { postId, reason, type: 'report', route: `/post/${postId}` },
        });
      }
    } catch {
      // notification failure should not block the report
    }
  },

  async searchUsersByUsername(query: string): Promise<{ id: string; username: string; fullName: string; avatar?: string }[]> {
    if (!query || query.length < 1) return [];
    const { data, error } = await (supabase
      .from('users')
      .select('id, username, full_name, avatar')
      .ilike('username', `${query}%`)
      .eq('is_banned', false)
      .limit(5) as any);

    if (error) return [];
    return ((data || []) as any[]).map((u) => ({
      id: u.id,
      username: u.username,
      fullName: u.full_name,
      avatar: u.avatar || undefined,
    }));
  },

  async sendMentionNotifications(content: string, authorId: string, postId: string, authorName: string): Promise<void> {
    const mentions = content.match(/@(\w+)/g);
    if (!mentions || mentions.length === 0) return;

    const usernames = [...new Set(mentions.map((m) => m.slice(1)))];
    if (usernames.length === 0) return;

    const { data: users } = await (supabase
      .from('users')
      .select('id, username')
      .in('username', usernames)
      .neq('id', authorId) as any);

    if (!users || users.length === 0) return;

    const { notificationsApi } = await import('@/lib/api/notifications');
    await notificationsApi.sendToMany(
      (users as any[]).map((u) => u.id),
      {
        type: 'social',
        title: 'Vous avez été mentionné',
        message: `${authorName} vous a mentionné dans un post`,
        data: { postId, type: 'mention', route: `/post/${postId}` },
      }
    );
  },

  async getLikers(postId: string, limit: number = 3): Promise<{ id: string; username: string; fullName: string; avatar?: string }[]> {
    const { data, error } = await (supabase
      .from('post_likes')
      .select('user_id')
      .eq('post_id', postId)
      .order('created_at', { ascending: false })
      .limit(limit) as any);

    if (error || !data || data.length === 0) return [];

    const userIds = (data as any[]).map((l) => l.user_id);
    const { data: users } = await (supabase
      .from('users')
      .select('id, username, full_name, avatar')
      .in('id', userIds) as any);

    return ((users || []) as any[]).map((u) => ({
      id: u.id,
      username: u.username,
      fullName: u.full_name,
      avatar: u.avatar || undefined,
    }));
  },

  async getAllReports(): Promise<{ id: string; postId: string; reporterId: string; reason: string; status: string; createdAt: Date; postContent?: string; postAuthorName?: string; reporterName?: string; reporterAvatar?: string }[]> {
    const { data, error } = await (supabase
      .from('post_reports')
      .select('id, post_id, reporter_id, reason, status, created_at')
      .order('created_at', { ascending: false }) as any);

    if (error) throw error;
    if (!data || data.length === 0) return [];

    const reports = data as any[];

    // Fetch post details
    const postIds = [...new Set(reports.map((r) => r.post_id))];
    const { data: posts } = await (supabase
      .from('posts')
      .select('id, content, author_id')
      .in('id', postIds) as any);

    // Fetch user details for reporters and post authors
    const reporterIds = [...new Set(reports.map((r) => r.reporter_id))];
    const authorIds = [...new Set((posts || []).map((p: any) => p.author_id))];
    const allUserIds = [...new Set([...reporterIds, ...authorIds])];

    const { data: users } = await (supabase
      .from('users')
      .select('id, username, full_name, avatar')
      .in('id', allUserIds) as any);

    const userMap = new Map<string, { fullName: string; avatar?: string }>();
    for (const u of (users || []) as any[]) {
      userMap.set(u.id, { fullName: u.full_name, avatar: u.avatar || undefined });
    }

    const postMap = new Map<string, { content: string; authorId: string }>();
    for (const p of (posts || []) as any[]) {
      postMap.set(p.id, { content: p.content, authorId: p.author_id });
    }

    return reports.map((r) => {
      const post = postMap.get(r.post_id);
      const reporter = userMap.get(r.reporter_id);
      const author = post ? userMap.get(post.authorId) : undefined;
      return {
        id: r.id,
        postId: r.post_id,
        reporterId: r.reporter_id,
        reason: r.reason,
        status: r.status,
        createdAt: new Date(r.created_at),
        postContent: post?.content,
        postAuthorName: author?.fullName,
        reporterName: reporter?.fullName,
        reporterAvatar: reporter?.avatar,
      };
    });
  },

  async updateReportStatus(reportId: string, status: string): Promise<void> {
    const { error } = await (supabase
      .from('post_reports')
      .update({ status })
      .eq('id', reportId) as any);

    if (error) throw error;
  },

  async adminDeletePost(postId: string): Promise<void> {
    const { error } = await (supabase
      .from('posts')
      .delete()
      .eq('id', postId) as any);

    if (error) throw error;
  },

  async adminDeleteComment(commentId: string): Promise<void> {
    const { error } = await (supabase
      .from('post_comments')
      .delete()
      .eq('id', commentId) as any);

    if (error) throw error;
  },

  async getPostComments(postId: string): Promise<PostComment[]> {
    return this.getComments(postId);
  },

  async getPostById(postId: string, currentUserId?: string): Promise<Post | null> {
    const { data, error } = await (supabase
      .from('posts')
      .select(`
        id, author_id, content, images, sport_tag, team_tag, match_tag, tournament_tag,
        is_auto_generated, auto_type, likes_count, comments_count, created_at,
        users!posts_author_id_fkey(username, full_name, avatar, is_verified)
      `)
      .eq('id', postId)
      .single() as any);

    if (error) {
      logger.error('PostsAPI', 'getPostById error:', error);
      return null;
    }
    if (!data) return null;

    const row = data as any;
    const author = row.users;
    let hasLiked = false;
    if (currentUserId) {
      const { data: like } = await (supabase
        .from('post_likes')
        .select('id')
        .eq('post_id', postId)
        .eq('user_id', currentUserId)
        .maybeSingle() as any);
      hasLiked = !!like;
    }

    return {
      id: row.id,
      authorId: row.author_id,
      content: row.content || '',
      images: row.images || [],
      sportTag: row.sport_tag || undefined,
      teamTag: row.team_tag || undefined,
      matchTag: row.match_tag || undefined,
      tournamentTag: row.tournament_tag || undefined,
      isAutoGenerated: row.is_auto_generated || false,
      autoType: row.auto_type || undefined,
      likesCount: row.likes_count || 0,
      commentsCount: row.comments_count || 0,
      createdAt: new Date(row.created_at),
      authorUsername: author?.username,
      authorFullName: author?.full_name,
      authorAvatar: author?.avatar || undefined,
      authorIsVerified: author?.is_verified,
      hasLiked,
    };
  },
};
